// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvkiw9e5Jj8MgZrxhZZnONJhVWyBmaKwM',
    appId: '1:112351982255:web:3ecc8dc121ce077ffdda5a',
    messagingSenderId: '112351982255',
    projectId: 'fintrack-5b736',
    authDomain: 'fintrack-5b736.firebaseapp.com',
    storageBucket: 'fintrack-5b736.firebasestorage.app',
    measurementId: 'G-JPKQVVJEZ3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbSCfJICtQjAc_X8vmDJm-ggjufIZZc7M',
    appId: '1:112351982255:android:7542c44b4d0a8ebcfdda5a',
    messagingSenderId: '112351982255',
    projectId: 'fintrack-5b736',
    storageBucket: 'fintrack-5b736.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFimKqtP8Ircd8H8_Ly_D3qs0BADmz5MQ',
    appId: '1:112351982255:ios:7af9213cca48862ffdda5a',
    messagingSenderId: '112351982255',
    projectId: 'fintrack-5b736',
    storageBucket: 'fintrack-5b736.firebasestorage.app',
    iosBundleId: 'com.example.fintrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFimKqtP8Ircd8H8_Ly_D3qs0BADmz5MQ',
    appId: '1:112351982255:ios:7af9213cca48862ffdda5a',
    messagingSenderId: '112351982255',
    projectId: 'fintrack-5b736',
    storageBucket: 'fintrack-5b736.firebasestorage.app',
    iosBundleId: 'com.example.fintrack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvkiw9e5Jj8MgZrxhZZnONJhVWyBmaKwM',
    appId: '1:112351982255:web:779cb03cabb035acfdda5a',
    messagingSenderId: '112351982255',
    projectId: 'fintrack-5b736',
    authDomain: 'fintrack-5b736.firebaseapp.com',
    storageBucket: 'fintrack-5b736.firebasestorage.app',
    measurementId: 'G-KLT76678T4',
  );
}
